version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sa.1
      MYSQL_DATABASE: msv_analisis
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring-kruger
  msv-usuarios:
    container_name: msv-usuarios
    build:
      context: ./
      dockerfile: ./msv-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./msv-usuarios/.env
    networks:
      - spring-kruger
    depends_on:
      - mysql8
    restart: always

  msv-analisis:
    container_name: msv-analisis
    build:
      context: ./
      dockerfile: ./msv-analisis/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./msv-analisis/.env
    networks:
      - spring-kruger
    depends_on:
      - mysql8
    restart: always

  msv-resultados:
    container_name: msv-resultados
    build:
      context: ./
      dockerfile: ./msv-resultados/Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./msv-resultados/.env
    networks:
      - spring-kruger
    depends_on:
      - mysql8
    restart: always


volumes:
  data-mysql:
    name: data-mysql
networks:
  spring-kruger: